{
  "formatVersion": "1.1",
  "component": {
    "group": "com.squareup.okhttp3",
    "module": "okhttp",
    "version": "4.10.0-CATS",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-4.10.0-CATS.jar",
          "url": "okhttp-4.10.0-CATS.jar",
          "size": 782731,
          "sha512": "c9fd0e56ccdbd946f271914d8666952d0b5188aa115305bb377b98156a8868314f71b9f6e0f06bf2b38beee446a4d87c0330ed0afe41c6c0b6a14f4825583efb",
          "sha256": "58a106ab9520a24c30ef2cbc72d5499b12cceb90064ed3a560b3c44434cd843a",
          "sha1": "f17c9b67517bea1168a08a3ac669f68c25bd57a9",
          "md5": "ed1390448de16e0ff3f45f21da913822"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okio",
          "module": "okio",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.6.20"
          }
        }
      ],
      "files": [
        {
          "name": "okhttp-4.10.0-CATS.jar",
          "url": "okhttp-4.10.0-CATS.jar",
          "size": 782731,
          "sha512": "c9fd0e56ccdbd946f271914d8666952d0b5188aa115305bb377b98156a8868314f71b9f6e0f06bf2b38beee446a4d87c0330ed0afe41c6c0b6a14f4825583efb",
          "sha256": "58a106ab9520a24c30ef2cbc72d5499b12cceb90064ed3a560b3c44434cd843a",
          "sha1": "f17c9b67517bea1168a08a3ac669f68c25bd57a9",
          "md5": "ed1390448de16e0ff3f45f21da913822"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "okhttp-4.10.0-CATS-javadoc.jar",
          "url": "okhttp-4.10.0-CATS-javadoc.jar",
          "size": 261,
          "sha512": "c4ac698c8291c5fd775af935a906a3adb1fa8f53e7954edf0015c7078c0643cbe9be263194516dbaa37e656be66b638e381653e3c379ee2570dcb3f79d5d9899",
          "sha256": "3af78893fd0dfb14d37bc3b2d105f87147cdeab62ce8a237fb801c766638d13a",
          "sha1": "51ac13c3cc330e2b8eef4244cebed3bc93af8ced",
          "md5": "2fc017f66ca048d829ed823f3ddafc33"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "okhttp-4.10.0-CATS-sources.jar",
          "url": "okhttp-4.10.0-CATS-sources.jar",
          "size": 364049,
          "sha512": "4a3859287f1fe212422da5f90cb7ba934fa3821990d5d4a68c824c6cff2f57c693620104d18eb45a3af2a370f46ac675bbee0b99714150312c134d69a1d05221",
          "sha256": "003ea65bc29c4d5d7fc5b310383a5978c10993a30118651c8e04d80d4014f889",
          "sha1": "6ed1a5c924f71066ef8d5d68947b3d0b6f215429",
          "md5": "2687cd13f8f17bdc08ec1b90c01b1bb6"
        }
      ]
    }
  ]
}
